server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html